<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-79LI2G12" ignored="0" name="RetryFailedTestcases" tests="8" failures="2" timestamp="31 Dec 2018 11:34:51 GMT" time="0.175" errors="0">
  <testcase name="test" time="0.025" classname="myTest.MyTest">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.0" classname="myTest.MyTest">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.015" classname="myTest.MyTest">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.002" classname="myTest.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at myTest.MyTest.test(MyTest.java:12)... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test2" time="0.0" classname="myTest.MyTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="myTest.MyTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.005" classname="myTest.MyTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="myTest.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at myTest.MyTest.test2(MyTest.java:16)... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- RetryFailedTestcases -->
